#!/usr/bin/env Rscript

# Heatmap (tile-style, no smoothing) for ADAM diversity/activity outputs.
# Input: .rds generated by ADAM::run_adam()

args <- commandArgs(trailingOnly = TRUE)

arg_value <- function(flag, default = NULL) {
    idx <- which(args == flag)
    if (length(idx) == 0L) {
        return(default)
    }
    val_idx <- idx[1] + 1L
    if (val_idx > length(args)) {
        stop(sprintf("Missing value for %s", flag))
    }
    args[val_idx]
}

ensure_bioc <- function(pkgs) {
    missing <- pkgs[!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]
    if (length(missing) == 0L) {
        return(invisible(TRUE))
    }
    if (!requireNamespace("BiocManager", quietly = TRUE)) {
        install.packages("BiocManager", repos = "https://cloud.r-project.org")
    }
    BiocManager::install(missing, ask = FALSE, update = FALSE)
    invisible(TRUE)
}

input_rds <- arg_value("--input")
if (is.null(input_rds)) {
    stop("Use --input path/to/result.rds")
}

output_png <- arg_value("--output", "outputs/models/entropy_activity_heatmap.png")
comparison_filter <- arg_value("--comparison", NULL)
top_n <- as.integer(arg_value("--top", "40"))
if (is.na(top_n) || top_n < 1L) {
    stop("--top must be a positive integer")
}

ensure_bioc(c("SummarizedExperiment", "S4Vectors", "ComplexHeatmap"))

library(SummarizedExperiment)
library(S4Vectors)
library(ComplexHeatmap)

res <- readRDS(input_rds)
if (!methods::is(res, "SummarizedExperiment")) {
    stop("Input object is not a SummarizedExperiment.")
}

metrics <- SummarizedExperiment::assay(res, "metrics")
rd <- as.data.frame(SummarizedExperiment::rowData(res), stringsAsFactors = FALSE)

if (!"ID" %in% colnames(rd)) {
    rd$ID <- rownames(rd)
}
if (!"Description" %in% colnames(rd)) {
    rd$Description <- rd$ID
}
if (!"Comparison" %in% colnames(rd)) {
    rd$Comparison <- "all"
}

if (is.null(comparison_filter)) {
    comparison_filter <- unique(as.character(rd$Comparison))[1]
}

sel <- as.character(rd$Comparison) == comparison_filter
if (!any(sel)) {
    stop(sprintf("No rows found for comparison: %s", comparison_filter))
}

rd <- rd[sel, , drop = FALSE]
metrics <- metrics[sel, , drop = FALSE]

wanted_cols <- grep("^(H_|N_|h$|n$)", colnames(metrics), value = TRUE)
if (length(wanted_cols) == 0L) {
    stop("No H_ / N_ / h / n columns found in metrics assay.")
}

mat <- as.matrix(metrics[, wanted_cols, drop = FALSE])
rownames(mat) <- make.unique(ifelse(is.na(rd$Description) | rd$Description == "", rd$ID, rd$Description))

# Prioritize terms with stronger departure in relative diversity/activity.
score <- rep(0, nrow(mat))
if ("h" %in% colnames(mat)) score <- score + abs(mat[, "h"] - 0.5)
if ("n" %in% colnames(mat)) score <- score + abs(mat[, "n"] - 0.5)
if (all(score == 0)) score <- rowSums(abs(mat), na.rm = TRUE)

keep <- order(score, decreasing = TRUE)
keep <- keep[seq_len(min(length(keep), top_n))]
mat <- mat[keep, , drop = FALSE]

# Z-score by column for comparability across scales (H/N/h/n).
scale_by_col <- function(x) {
    s <- stats::sd(x, na.rm = TRUE)
    if (is.na(s) || s == 0) {
        return(rep(0, length(x)))
    }
    (x - mean(x, na.rm = TRUE)) / s
}
mat_z <- apply(mat, 2, scale_by_col)
mat_z <- as.matrix(mat_z)
rownames(mat_z) <- rownames(mat)
colnames(mat_z) <- colnames(mat)

out_dir <- dirname(output_png)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

grDevices::png(output_png, width = 1600, height = 1200, res = 160)
ht <- ComplexHeatmap::Heatmap(
    mat_z,
    name = "z-score",
    cluster_rows = TRUE,
    cluster_columns = FALSE,
    row_names_gp = grid::gpar(fontsize = 7),
    column_names_gp = grid::gpar(fontsize = 9),
    heatmap_legend_param = list(direction = "horizontal")
)
ComplexHeatmap::draw(ht, heatmap_legend_side = "bottom")
graphics::title(main = paste0("ADAM diversity/activity heatmap | comparison: ", comparison_filter))
grDevices::dev.off()

message("Saved heatmap: ", output_png)
