// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// MakeBootstrap
NumericMatrix MakeBootstrap(NumericMatrix BootstrapData, int BootstrapNumber, int BootstrapGroupSize, double BootstrapSeed);
RcppExport SEXP _ADAM_MakeBootstrap(SEXP BootstrapDataSEXP, SEXP BootstrapNumberSEXP, SEXP BootstrapGroupSizeSEXP, SEXP BootstrapSeedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type BootstrapData(BootstrapDataSEXP);
    Rcpp::traits::input_parameter< int >::type BootstrapNumber(BootstrapNumberSEXP);
    Rcpp::traits::input_parameter< int >::type BootstrapGroupSize(BootstrapGroupSizeSEXP);
    Rcpp::traits::input_parameter< double >::type BootstrapSeed(BootstrapSeedSEXP);
    rcpp_result_gen = Rcpp::wrap(MakeBootstrap(BootstrapData, BootstrapNumber, BootstrapGroupSize, BootstrapSeed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ADAM_MakeBootstrap", (DL_FUNC) &_ADAM_MakeBootstrap, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ADAM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
